# -*- coding: utf-8 -*-
"""agent.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yg8bF4WIlIuA67_GP4kt4GLh6XO7G1bX
"""

from groq import Groq
from dotenv import load_dotenv
import os

load_dotenv()

def get_budget_plan(summary):
    client = Groq(
        api_key=os.getenv("GROQ_API_KEY")
    )

    prompt = f"""
    You are a financial advisor AI.

    Here is user's spending summary:
    {summary}

    Generate:
    1. Spending analysis
    2. Overspending categories
    3. Monthly budget plan
    4. Money saving tips
    5. Risk alerts (if any)
    """
    response = client.chat.completions.create(
        model="openai/gpt-oss-120b",
        messages=[{"role": "user", "content": prompt}]
    )

    return response.choices[0].message.content